name: micro_journal
description: The Micro Journal is a modern, feature-rich application designed to help users practice daily self-reflection and track their mental well-being in a simple, engaging way.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  feedback: ^3.2.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_email_sender: ^8.0.0
  flutter_local_notifications: ^19.2.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  glassmorphism: ^3.0.0
  go_router: ^14.2.3
  google_fonts: ^6.3.0
  google_sign_in: ^6.2.2
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  logman: ^0.0.20
  path_provider: ^2.1.5
  reactive_forms: ^17.0.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  solar_icons: ^0.0.5
  table_calendar: ^3.1.3
  timezone: ^0.10.1
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

#  fonts:
#    - family: Noto Sans
#      fonts:
#        - asset: assets/fonts/NotoSans/NotoSans-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/NotoSans/NotoSans-ThinItalic.ttf
#          weight: 100
#          style: italic
#        - asset: assets/fonts/NotoSans/NotoSans-ExtraLight.ttf
#          weight: 200
#        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
#          weight: 400
#          style: italic
#        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/NotoSans/NotoSans-MediumItalic.ttf
#          weight: 500
#          style: italic
#        - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
#          weight: 700
#          style: italic
#        - asset: assets/fonts/NotoSans/NotoSans-Black.ttf
#          weight: 900
